version: 2
updates:
  - package-ecosystem: uv
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      pydantic:
        applies-to: security-updates
        patterns:
          - "pydantic"
          - "pydantic-core"
      aws-sdk:
        applies-to: security-updates
        patterns:
          - "boto3"
          - "botocore"
          - "s3transfer"
      fastapi:
        applies-to: security-updates
        patterns:
          - "fastapi"
          - "starlette"
